### ISSUE TITLE
Still problems with bash-files in release 2.1.40

### ISSUE THREAD

**Issue by BBATools** [sfa-siard/SiardCmd#2] opened 2018-04-17 12:16 UTC
~/Downloads/siardcmd (2) $ ./siardfromdb.sh 
bash: ./siardfromdb.sh: /bin/sh^M: bad interpreter: No such file or directory

~/Downloads/siardcmd (2) $ ./siardtodb.sh 
bash: ./siardtodb.sh: /bin/sh^M: bad interpreter: No such file or directory

Solved it locally with the dos2unix command.

**Comment by HartwigThomas** [comment] 2018-04-20 16:06
I learned, that Git will not check in a file, where just the CRLFs have been replaced by LFs.
The problem is fixed in SiardCmd v2.1.49 and in SiardGui v2.1.66 (SIARD-Suite-2.1.66.zip)

**Closed by HartwigThomas** 2018-04-20 16:06 UTC
